name: GitHub Pages for HW-2
run-name: ${{ github.actor }} - GitHub Pages for Homework 2
on: 
  push:
    branches:
      - hw-2
permissions:
  pages: write
  id-token: write
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install Dependencies
      working-directory: ./hw-2
      run: npm i
    - name: Build Production
      working-directory: ./hw-2
      run: npm run prod
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./hw-2/build
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./hw-2/build
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
